language: python

python:
  - "2.7_with_system_site_packages"

env:
  - TOX_ENV=py27
  - TOX_ENV=py27-tornado23
  - TOX_ENV=py27-tornado31
  - TOX_ENV=docs
  - TOX_ENV=flake8

install:
  - "wget -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add -"
  - "sudo wget -O /etc/apt/sources.list.d/mopidy.list http://apt.mopidy.com/mopidy.list"
  - "sudo apt-get update || true"
  - "sudo apt-get install mopidy graphviz-dev"
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"

branches:
  except:
    - debian

notifications:
  irc:
    channels:
      - "irc.freenode.org#mopidy"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
